const fs=require('fs');
const assert=require('assert');
const engine=fs.readFileSync(__dirname+'/economy-engine.js','utf8');
const css=fs.readFileSync(__dirname+'/economy.css','utf8');
const html=fs.readFileSync(__dirname+'/snap-draft.html','utf8');
const shop=fs.readFileSync(__dirname+'/economy-shop-core.js','utf8');

assert.match(html,/economy\.css\?v=2\.6\.0-shop-refinement/);
assert.match(html,/economy-engine\.js\?v=2\.5\.0-shop-refinement/);
assert.match(html,/economy-shop-core\.js\?v=2\.5\.1/);
assert.match(engine,/economy-shop-launcher-art/);
assert.match(engine,/cosmic_shop_planet\.png/);
assert.match(engine,/economy-product-row-primary/);
assert.match(engine,/economy-product-row-secondary/);
assert.match(engine,/economy-product-row-extensions/);
assert.match(engine,/economy-product-card-v2/);
assert.match(engine,/economy-product-v2-art-wrap/);
assert.match(engine,/economy-product-v2-price-zone/);
assert.match(engine,/catalog\.slice\(0,5\)/);
assert.match(engine,/catalog\.slice\(5,10\)/);
assert.match(engine,/asset-missing/);
assert.doesNotMatch(engine,/data-economy-ledger/);
assert.match(engine,/shop_page_arrow_left\.png/);
assert.match(engine,/shop_page_arrow_right\.png/);
assert.match(engine,/shop_customer_panel\.png/);
assert.match(engine,/shop_wallet_panel_v2\.png/);
assert.match(engine,/FLASH SALE −50%/);
assert.match(engine,/showCheckout\?\.\(result\.price/);
assert.match(css,/aspect-ratio:3\/2!important/);
assert.match(css,/JEFF'S COSMIC SHOP UI V2/);
assert.match(css,/grid-template-rows:auto minmax\(0,1fr\) auto auto!important/);
assert.match(css,/economy-product-v2-price-zone/);
assert.match(css,/economy-extension-seal/);
assert.match(css,/object-fit:cover!important/);
assert.match(css,/shop_unavailable_strip\.png/);
assert.match(css,/shop_footer_info_tile\.png/);
assert.match(engine,/shop_exit_tile\.png/);
assert.match(css,/economy-wallet-strip\.economy-wallet-compact\{\n    width:100%!important/);
assert.match(css,/url\("draft-assets\/cosmic_shop_background\.png"\) center\/cover no-repeat!important/);
assert.match(css,/economy-checkout-burst/);
assert.match(shop,/function showCheckout\(/);
assert.match(shop,/showCheckout,/);
assert.match(css,/economy-shop-opened #jokerV2ResolveModal\.joker-v2-overlay\{z-index:31050!important;\}/);
assert.match(shop,/has-child-modal/);
console.log('Economy E2.2E pixel-match regression OK');
