const fs=require('fs');
const assert=require('assert');
const engine=fs.readFileSync(__dirname+'/economy-engine.js','utf8');
const css=fs.readFileSync(__dirname+'/economy.css','utf8');
const html=fs.readFileSync(__dirname+'/snap-draft.html','utf8');
assert.match(html,/economy\.css\?v=2\.6\.1-shop-recovery/);
assert.match(html,/economy-engine\.js\?v=2\.5\.1-shop-recovery/);
assert.match(engine,/economy-shop-floating-coin coin-10/);
assert.match(engine,/is-name-very-long/);
assert.match(engine,/nameLength>20/);
assert.match(css,/PATCH112E — JEFF'S COSMIC SHOP REFINEMENT/);
assert.match(css,/font-family:"Bungee","Fredoka"/);
assert.match(css,/economy-product-v2-price-zone::before/);
assert.match(css,/url\("draft-assets\/jeffcoin\.png"\)/);
assert.match(css,/economyShopCoinFloat112E/);
assert.match(css,/\.coin-10/);
assert.match(css,/economy-shop-balance-coin\{display:none!important;\}/);
assert.match(css,/left:39%!important/);
assert.match(css,/economy-shop-pages\{[\s\S]*?inset:22\.6%/);
assert.match(css,/gap:2\.05%!important/);
assert.match(css,/economy-shop-close span\{[\s\S]*?Bungee/);
console.log('PATCH112E shop refinement regression OK');
