const fs=require('fs');
const assert=require('assert');
const css=fs.readFileSync(__dirname+'/economy.css','utf8');
const engine=fs.readFileSync(__dirname+'/economy-engine.js','utf8');
const shop=fs.readFileSync(__dirname+'/economy-shop-core.js','utf8');
const html=fs.readFileSync(__dirname+'/snap-draft.html','utf8');
assert.match(html,/economy\.css\?v=2\.7\.0-shop-patch-b/);
assert.match(html,/economy-engine\.js\?v=2\.7\.0-shop-patch-b/);
assert.match(html,/economy-shop-core\.js\?v=2\.7\.0-shop-patch-b/);
assert.match(engine,/ZAKUPY ŁĄCZNIE/);
assert.match(engine,/cosmic_sale_product_ribbon\.png/);
assert.match(engine,/economy-shop-sale-meter/);
assert.match(css,/shop_footer_shelf_left\.png/);
assert.match(css,/shop_footer_shelf_center\.png/);
assert.match(css,/shop_footer_shelf_right\.png/);
assert.match(css,/economy-product-v2-promo\.is-cosmic-sale-ribbon/);
assert.match(css,/\.economy-shop-mini-cost\{left:6\.5%!important;\}/);
assert.match(css,/\.economy-shop-mini-power\{right:6\.5%!important;\}/);
assert.match(css,/economyPatch113BChooserPan/);
assert.match(css,/economyPatch113BClientRgb/);
assert.match(shop,/has-shop-info/);
assert.match(shop,/is-shelf-confirm/);
assert.match(shop,/Wskaż własną kartę, a sklep pokaże 5 losowych propozycji/);
assert.match(shop,/Wskaż własną kartę, a sklep pokaże 8 losowych propozycji/);
console.log('PATCH113B FULL SHOP regression checks passed.');
